### ISSUE TITLE
Webcam-a ireki eta segidan itxi

### ISSUE THREAD

**Issue by ionhs** [mikelalda/Tknika_eskuen_detekzioa#2]
Kaixo ez dakit honi jarraikortasuna emango diozun baina galdetzearren: Instalazio pausuak osatzea lortu dut baina azken instrukzioa idaztean webcam lehioa ireki egiten da, nire imagina eta goian eskurik gabe testu batekin. Segidan lehioa itxi egin da. Hau da eman du informazio guztia

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Esku_ardatz_detekzioa.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  landmark_csv = landmark_csv.append(a_series, ignore_index=True)
Traceback (most recent call last):
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 106, in normalize_element
    spec = type_spec_from_value(t, use_fallback=False)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 479, in type_spec_from_value
    raise TypeError("Could not build a TypeSpec for %r with type %s" %
TypeError: Could not build a TypeSpec for         0_x       0_y  0_z       1_x  ...      19_z      20_x      20_y      20_z
0  0.703454  0.752299 -0.0  0.641066  ... -0.098952  0.278209  0.936047 -0.096867

[1 rows x 63 columns] with type DataFrame

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Esku_ardatz_detekzioa.py", line 68, in <module>
    hand_landmark_result = int(np.argmax(new_model.predict(landmark_csv)))
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1696, in predict
    data_handler = data_adapter.get_data_handler(
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1364, in get_data_handler
    return DataHandler(*args, **kwargs)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1154, in __init__
    self._adapter = adapter_cls(
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 339, in __init__
    dataset = self.slice_inputs(indices_dataset, inputs)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 365, in slice_inputs
    dataset_ops.DatasetV2.from_tensors(inputs).repeat()
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 681, in from_tensors
    return TensorDataset(tensors)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3301, in __init__
    element = structure.normalize_element(element)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 111, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

**Comment by ionhs** [comment]
pausu hauek jarraitu ditut https://www.codegrepper.com/code-examples/python/pip+install+tensorflow%3D%3D1.13.2 pythona instalatu eta ondoren tensorflow. 

Orain imagina ez da izten eskua azaldu arte pantailan. Susmoa dut nire eskua ez duela errekonozitzen eta horrek faila arazten duela. 

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Esku_ardatz_detekzioa.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  landmark_csv = landmark_csv.append(a_series, ignore_index=True)
Traceback (most recent call last):
  File "Esku_ardatz_detekzioa.py", line 68, in <module>
    hand_landmark_result = int(np.argmax(new_model.predict(landmark_csv)))
  File "/home/tknika/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/tknika/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

**Comment by mikelalda** [comment]
Epa Ion!! 

Ez daukat asmorik jarraipena emateko, baina ematen du modeloari puntuak pasatzean zerbaitek errorea ematen duela. Puntuak nola pasatzen dizkiozun begiratu behar, agian zutabetako titulu gabe. 

Ea lortzen duzun!!

**Comment by mikelalda** [comment]
orain requirements erabilita instalatzen baduzu zuzenean egin beharko lizuke aldaketarik egin gabe.
